-- ============================================================================
-- 00000000100116_visual_schedule_cdef.sql
-- ============================================================================
-- Build M Sub-phase A — visual_schedule library expansion (Grids C/D/E/F)
--
-- Adds 64 new paper-craft icons to the platform_assets visual_schedule
-- catalog, raising the total from 328 → 392 rows. These are the gap-fill
-- icons covering daily essentials, faith/disability/kindness, morning/
-- evening routines, and emotional regulation & social skills.
--
-- Storage URLs are already populated in production (uploaded by the
-- ingestion script). The migration body is a single INSERT block with
-- ON CONFLICT (feature_key, variant, category) DO NOTHING for safe re-runs.
--
-- Generated by:
--   1. scripts/ingest-cdef-icons.cjs (vision + embeddings + storage upload)
--   2. scripts/generate-cdef-icons-sql.cjs (JSON → INSERT VALUES SQL)
--
-- Source manifests:
--   - seed-assets/visual-schedule-icons-cdef/vs-grid-c2.png (Daily Essentials)
--   - seed-assets/visual-schedule-icons-cdef/vs-grid-d2.png (Faith, Disability, Kindness)
--   - seed-assets/visual-schedule-icons-cdef/vs-grid-e.png  (Morning & Evening Routine)
--   - seed-assets/visual-schedule-icons-cdef/vs-grid-f.png  (Emotional Regulation & Social)
-- ============================================================================

BEGIN;

